apiVersion: v1
kind: Secret
metadata:
  name: deid-db-secret
type: Opaque
data:
  MYSQL_DATABASE: 'ZGVpZA=='
  MYSQL_PASSWORD: 'MTIz'
  MYSQL_ROOT_PASSWORD: 'QWExMjM='
  MYSQL_USER: 'cmFpZmU='
  MYSQL_HOST: 'ZGVpZC1kYg=='

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deid-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deid-db
  template:
    metadata:
      labels:
        app: deid-db
    spec:
      containers:
        - name: deid-db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: deid-db-secret
          volumeMounts:
            - mountPath: /home/docker/mysql
              name: dbdata
      restartPolicy: Always
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: dbdata

---

apiVersion: v1
kind: Service
metadata:
  name: deid-db
spec:
  selector:
    app: deid-db
  ports:
    - port: 3306
      targetPort: 3306


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbdata
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/dbdata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
